services: 
  server:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - docker-service
    environment:
      NODE_ENV: production
    depends_on:
      - mariadb 
      - mongo   
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'
    networks:
      - docker-service
  mariadb:
    image: mariadb:latest
    container_name: templating-mariadb
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db   
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7
      # image: phpmyadmin/phpmyadmin
      container_name: templating-phpmyadmin
      ports: 
        - 8091:80
      #links:
      #  - mysql 
      environment:
        PMA_HOST: mariadb 
      depends_on:
        - mariadb          
      networks:
        - docker-service   
networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local